### ISSUE TITLE
Why do I have to instantiate an instance of Parser() to use this?

### ISSUE THREAD

**Issue by onlywei** [webantic/nginx-config-parser#2]
The documentation is not what I am experiencing when I try to use this. Here's my code:

```
import parser from '@webantic/nginx-config-parser';

parser.readConfigFile('path/to/file'); // error
new Parser().readConfigFile('path/to/file'); // succeeds
```

Is this intentional?

**Comment by carlevans719** [comment]
Thanks for flagging this - I've updated the readme in ee4cf2c40ac92b50fd8a1b88aafa4448229a05a6 to reflect the correct usage
